# Generated by Django 2.0.6 on 2018-06-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.TextField(default='&#8373;', max_length=50),
        ),
    ]
